### ISSUE TITLE
(ansible 2.15) error remote username contains invalid characters

### ISSUE THREAD

**Issue by mehdia4ever** [psvmcc/ansible-collection-mitogen#17]
Hi,

Am using ansible core 2.15.6 in Tower with serverscom.mitogen collections and am getting this issue.

In my ansible inventory file, am using bastion server to connect to my hosts target with a specific user setting with a variable {{ user_name }}

**SERVERNAME ansible_host="bastion" ansible_user="root@SERVERNAME:SSH:{{ user_name }}"**

I set the value of the [user_name] in extra vars but am having this error message when am running the job.

**SERVERNAME | UNREACHABLE! => {
    "changed": false,
    "msg": "EOF on stream; last 100 lines received:\nremote username contains invalid characters\r",
    "unreachable": true**

When i set manuely the value of variable {{ user_name }} in inventory file, it Works.

Please, if you have any suggestions.

ansible [core 2.15.6]
  config file = None
  configured module search path = ['/.ansible/plugins/modules', '/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True

ANSIBLE_TIMEOUT=40
ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear
ANSIBLE_HOST_KEY_CHECKING=False
ANSIBLE_PIPELINING=True

pip list
mitogen                              0.3.4

Collection                               Version
amazon.aws                               7.2.0
serverscom.mitogen                       1.3.4

**Comment by mehdia4ever** [comment]
@amarao @psvmcc do you have any ideas about this issue ?

**Comment by amarao** [comment]
It looks like usual mitogen 'bleeding edge'. It's either should be fixed in mitogen upstream, or 'fixed' by using strategy:linear on affected play.

**Comment by mehdia4ever** [comment]
Thank's @amarao adding strategy: linear is not the solution for me, the execution is to much slow without mitogen.
I cannot keep this config without mitogen, do you have any ideas to fix it ?

**Comment by amarao** [comment]
Try to split to few plays with linear only for affected tasks.

Unfortunately, we do not provide support for mitogen, there is separate repo for this.

This repo is just a wrapper over mitogen to use it as collection.

**Comment by amarao** [comment]
Closing issue as related to Mitogen itself.
